
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-6pm-1
owner: ucsb-cs156-f23
repo_name: team02-f23-6pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjIyNDU0MjE4","is_bot":false,"login":"Dagin-Gregory","name":"Dagin Gregory"},"headRefName":"DG","number":52,"title":"Added CRUD operations + Associated tests & Dokku personal dev deployment","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-1/pull/52"},{"author":{"id":"U_kgDOBXj-Bg","is_bot":false,"login":"chauAlex","name":""},"headRefName":"Alex-DELETERecRequest","number":51,"title":"Added DELETE endpoint for RecommendationRequestTable","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-1/pull/51"},{"author":{"id":"U_kgDOBXj-Bg","is_bot":false,"login":"chauAlex","name":""},"headRefName":"Alex-PUTRecRequest","number":50,"title":"Added PUT endpoint for RecommendationRequestTable","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-1/pull/50"},{"author":{"id":"U_kgDOBXj-Bg","is_bot":false,"login":"chauAlex","name":""},"headRefName":"Alex-GETSingleRecRequest","number":49,"title":"Added GET (show) endpoint for single record in RecommendationRequestTable","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-1/pull/49"},{"author":{"id":"MDQ6VXNlcjQ0Njg5MjQw","is_bot":false,"login":"Johnsonchan105","name":"Johnson Chan"},"headRefName":"Johnson-OrgRequestTable","number":46,"title":"Created UCSB Organization Entity and Repository","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-1/pull/46"}]
